### ISSUE TITLE
Delete your GA id from source code

### ISSUE THREAD

**Issue by txusinho** [dominic-braeunlein/google-analytics-with-ludei-cocconjs-canvas#1]
For your safety ;-)

**Comment by dominic-braeunlein** [comment]
Seems like I'm super blind :) I can't find it. Can you tell me where you found it?

**Comment by txusinho** [comment]
https://github.com/dominic-braeunlein/google-analytics-with-ludei-cocconjs-canvas/blob/master/index.html#L73

**Comment by dominic-braeunlein** [comment]
I see, this is confusing. This is just a random UUID that I used instead of the deviceID. Will delete it anyway. Thank you!

**Comment by txusinho** [comment]
I was just reading and saw the ID, It seemed the GA id.
My fault. sorry ¬¬U
